/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academic;

/**
 *
 * @author ALING
 */import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class inputmahasiswa extends javax.swing.JFrame {
private final DefaultTableModel model;
static Connection conn = null;
static Statement stmt = null;
static String nim, pass, nama, uts,tugas, grade, sql, cmd, tlahir, tgll, contact, email, kelas, fakultas,gender;
static ResultSet rs;
    /**
     * Creates new form inputmahasiswa
     */
    public inputmahasiswa() {
        initComponents();
         model = new DefaultTableModel();
        datamahasiswa.setModel(model);
        model.addColumn("NIM");
        model.addColumn("NAMA");
        model.addColumn("PASS");
         model.addColumn("Tempat Lahir");
          model.addColumn("Tanggal Lahir");
           model.addColumn("Gender");
           model.addColumn("Fakultas");
           model.addColumn("Kelas");
            model.addColumn("Contact");
             model.addColumn("Email");
              try{
                  jComboBox1.removeAllItems();
                
            conn = DriverManager.getConnection("jdbc:mysql://localhost/tugas","root", "ABC");
            stmt  = conn.createStatement();
            cmd = "SELECT * FROM fakultas";
            rs = stmt.executeQuery(cmd);  
            while(rs.next()){
                jComboBox1.addItem(rs.getString("nama"));
            }rs.last();
             rs.getRow();
            rs.first();
            }catch (SQLException e){
                System.out.println(e.getMessage());
            }
              try{
                    jComboBox2.removeAllItems();
                  jComboBox3.removeAllItems();
            conn = DriverManager.getConnection("jdbc:mysql://localhost/tugas","root", "ABC");
            stmt  = conn.createStatement();
            cmd = "SELECT * FROM combo";
            rs = stmt.executeQuery(cmd);  
            while(rs.next()){
                  jComboBox2.addItem(rs.getString("kelas"));
                jComboBox3.addItem(rs.getString("gender"));
            }rs.last();
            rs.getRow();
            rs.first();
            }catch (SQLException e){
                System.out.println(e.getMessage());
            }
        loadData();
     
    }
    public final void loadData(){
        model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/tugas","root", "ABC");
            stmt  = conn.createStatement();
            cmd = "SELECT * FROM mahasiswa order by nim";
            rs = stmt.executeQuery(cmd);
            while(rs.next()){
                nim= rs.getString("nim");
                nama = rs.getString("nama");
                pass = rs.getString("pass");
                tlahir = rs.getString("tlahir");
                tgll = rs.getString("tgll");
                gender= rs.getString("gender");
                fakultas = rs.getString("fakultas");
                contact = rs.getString("contact");
                email = rs.getString("email");
                 kelas = rs.getString("kelas");
                model.addRow(new Object[]{nim, nama, pass,tlahir,tgll,gender,fakultas,kelas,contact,email});
}rs.close();
        }catch (SQLException e){
    JOptionPane.showMessageDialog(null,"Terjadi ERROR");
    }
}
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        datamahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel2.setText("PASS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 205, 354, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 243, 354, -1));

        jButton1.setText("INPUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 585, -1, -1));

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 585, -1, -1));

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 585, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("DATA MAHASISWA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel4.setText("NIM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 27, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 281, 354, -1));

        jLabel5.setText("Tempat Lahir");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 319, 354, -1));

        jTextField5.setText("YYYYMMDD");
        jTextField5.setToolTipText("");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 357, 354, -1));

        jLabel6.setText("Tanggal Lahir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 79, -1));

        jLabel7.setText("Fakultas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 436, -1, -1));

        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 550, -1, -1));

        jLabel9.setText("Contact");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 512, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 509, 354, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 547, 354, -1));

        jLabel10.setText("Kelas");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 474, -1, -1));

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 585, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 433, 354, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 471, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 395, -1, -1));

        jLabel11.setText("Gender");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALING\\Pictures\\uph.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 360, 140));

        jInternalFrame1.setVisible(true);

        datamahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(datamahasiswa);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
nim = jTextField1.getText();
conn = DriverManager.getConnection("jdbc:mysql://localhost/tugas","root", "ABC");
cmd = "DELETE FROM mahasiswa WHERE nim = ?";
PreparedStatement ps = conn.prepareStatement(cmd);
   ps.setString(1,nim);
   ps.executeUpdate();
        ps.close();
}catch (SQLException e){
    System.out.println("Terjadi Error");
}finally {
    loadData();
   jTextField1.setText("");
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
nim = jTextField1.getText();
nama = jTextField2.getText();
pass = jTextField3.getText();
tlahir= jTextField4.getText();
tgll = jTextField5.getText();
gender = (String) jComboBox3.getSelectedItem();
fakultas = (String) jComboBox1.getSelectedItem();
contact= jTextField7.getText();
email = jTextField8.getText();
kelas = (String) jComboBox2.getSelectedItem();
cmd = "INSERT INTO mahasiswa VALUES(?,?,?,?,?,?,?,?,?,?)";

conn = DriverManager.getConnection("jdbc:mysql://localhost/tugas","root", "ABC");
 PreparedStatement ps = conn.prepareStatement(cmd);
        ps.setString(1,nim);
        ps.setString(2,nama);
        ps.setString(3,pass);
        ps.setString(4,tlahir);
        ps.setString(5,tgll);
        ps.setString(6,fakultas);
        ps.setString(7,contact);
        ps.setString(8,email);
        ps.setString(9,kelas);
        ps.setString(10,gender);
        ps.executeUpdate();
        ps.close();
}catch (SQLException e){
    }finally {
    loadData();
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
nim = jTextField1.getText();
nama = jTextField2.getText();
pass = jTextField3.getText();
tlahir= jTextField4.getText();
tgll = jTextField5.getText();
gender = (String) jComboBox3.getSelectedItem();
fakultas = (String) jComboBox1.getSelectedItem();
contact= jTextField7.getText();
email = jTextField8.getText();
kelas = (String) jComboBox2.getSelectedItem();
conn = DriverManager.getConnection("jdbc:mysql://localhost/tugas","root", "ABC");
cmd = "UPDATE mahasiswa SET nama = ?,pass = ?,tlahir = ?,tgll = ?,gender = ?,fakultas = ?, contact = ?,email = ?,kelas=? WHERE nim = ?";
PreparedStatement ps = conn.prepareStatement(cmd);
        ps.setString(1,nama);
        ps.setString(2,pass);
        ps.setString(3,tlahir);
        ps.setString(4,tgll);
        ps.setString(5, gender);
        ps.setString(6,fakultas);
        ps.setString(7, contact);
        ps.setString(8,email);
        ps.setString(9,kelas);
        ps.setString(10,nim);
        ps.executeUpdate();
        ps.close();
}catch (SQLException e){
    System.out.println("Terjadi Error");
}finally {
    loadData();
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 this.setVisible(false);
        new input().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputmahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable datamahasiswa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
